```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=FALSE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here


# end setup chunk
```

#http://stackoverflow.com/questions/13443372/simple-way-to-subset-spatialpolygonsdataframe-i-e-delete-polygons-by-attribut

# http://stackoverflow.com/questions/22525647/r-highlighting-some-of-the-boundaries-or-borders-of-the-region-in-a-shape-file

Topico ligado aos s3_08=7 e s3_08

# Pegar as coordenadas de um polígono específico

```{r}
## 1 Pegar os polígonos do shape
shape_ListaPoligonos <- dados_municipios@polygons;
## 2 Pegar os dados de um polígono específico
SubPoligono_dados <- slot(shape_ListaPoligonos[[4]],"Polygons");
class(SubPoligono_dados);
## 3 Transforma da estrutura lista para a estrutura Polygon
SubPoligono_dados <- SubPoligono_dados[[1]];
class(SubPoligono_dados);
## 4 Pega as coordenadas do subpolígono
SubPoligono_coordenadas <- SubPoligono_dados@coords;
```
