```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=FALSE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here


# end setup chunk
```

# Conhecer as coordenadas min e max tanto em x quanto em y de um shape

```{r}
dados_municipios@bbox
plot( dados_municipios, axes=TRUE );
points( x=dados_municipios@bbox[1,1], y=dados_municipios@bbox[2,1], col="blue" );
points( x=dados_municipios@bbox[1,2], y=dados_municipios@bbox[2,1], col="blue" );
points( x=dados_municipios@bbox[1,2], y=dados_municipios@bbox[2,2], col="blue" );
points( x=dados_municipios@bbox[1,1], y=dados_municipios@bbox[2,2], col="blue" );
```

# Versão 2

```{r}
# Pegar as coordenadas dos polígonos de um shape
library("ggplot2");
Shape_coordenadas <- fortify(dados_municipios);

# Acrescentar umas linhas de código aqui, dá para pegar o min e max e um poligono especifico

Shape_coordenadas_MinMax <- apply(Shape_coordenadas[,c("long", "lat")], 2, range);
plot( dados_municipios, axes=TRUE );
points( x=Shape_coordenadas_MinMax[1,1], y=Shape_coordenadas_MinMax[1,2] );
points( x=Shape_coordenadas_MinMax[2,1], y=Shape_coordenadas_MinMax[1,2] );
points( x=Shape_coordenadas_MinMax[2,1], y=Shape_coordenadas_MinMax[2,2] );
points( x=Shape_coordenadas_MinMax[1,1], y=Shape_coordenadas_MinMax[2,2] );
```
