```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=FALSE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here


# end setup chunk
```

# Como selecionar apenas as rodovias que passam por SP?

```{r}
rodovias_rgdal <- readOGR(dsn="shapefiles/Shapefiles", layer="ST_DNIT_Rodovias_SNV2015_03", verbose=FALSE, stringsAsFactors=FALSE);
## 1 Encontrar o indice numérico correspondente ao município desejado
indices_rodovias_SP <- which( rodovias_rgdal@data$uf=="SP" );
## 2 Pegar as coordenadas das linhas do município desejado
dados_rodovias_SP <- rodovias_rgdal[indices_rodovias_SP, ];
## 3 Fazer o plot
plot( dados_rodovias_SP, axes=TRUE, col="yellow", lwd=3 )

sp_uf <- readOGR(dsn="sp_unidades_da_federacao", layer="35UFE250GC_SIR", 
                 verbose=FALSE, stringsAsFactors=FALSE);
plot(sp_uf, add=TRUE, axes=TRUE);
```
